baseURL = "http://dwtechnologies.github.io"
languageCode = "en-us"
title = "Daniel Welington"
copyright = "Â©2018"
theme = "dw"
HUGO_ENV = "production"
publishdir = "./"

[params]
    #To prevent most search engine web crawlers from indexing a page on your
    # noindex = true 

    #Hero section config
    heroTitle = "Open Source at Daniel Wellington"
    heroSubtitle = "It is time to contribute back to the community"
    heroImgSrc = "hero-banner.jpg"

    #see more button 
    seeMoreHref = "https://github.com/dwtechnologies"

    #footer section config
    footerTitle = "JOIN OUR MOVEMENT"
